site_name:        Spectra.jl
repo_url:         https://github.com/charlesll/Spectra.jl
site_description: A Julia library to help treating spectroscopic data.
site_author:      Charles Le Losq

theme: mkdocs

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite

docs_dir: 'build'

pages:
  - Home: index.md
  - Installation: Installation.md
  - Pre-Processing: PreProcessing.md
  - General Functions: GeneralFunctions.md
  - Rameau: Rameau.md
  - Machine Learning Regression: MLregressor.md
  - Peak Fitting: PeakFitting.md
  - Tutorial: Tutorial.md
  - Tips: Tips.md
  - Todo: ToDo.md
  - References: References.md